// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQJ6uiNhIHiclXmeN6Z3hNkPoPoEiHc8g',
    appId: '1:463452612456:web:9dfbb741523ad9c1c8d8dd',
    messagingSenderId: '463452612456',
    projectId: 'pharmadirect-a8570',
    authDomain: 'pharmadirect-a8570.firebaseapp.com',
    storageBucket: 'pharmadirect-a8570.appspot.com',
    measurementId: 'G-WELRXCNE88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlDbtDoMIS9hgg7y5CRKe6eLq_SEyZzmE',
    appId: '1:463452612456:android:3d23b8eaa5f2bfbec8d8dd',
    messagingSenderId: '463452612456',
    projectId: 'pharmadirect-a8570',
    storageBucket: 'pharmadirect-a8570.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBawMwyzzUzbUKncEwtVjFA18KHdmQqEFk',
    appId: '1:463452612456:ios:175b5a81e876e2ffc8d8dd',
    messagingSenderId: '463452612456',
    projectId: 'pharmadirect-a8570',
    storageBucket: 'pharmadirect-a8570.appspot.com',
    iosBundleId: 'com.example.pharmacyApp',
  );

}